/' ==============================================

Common section containing alias and styles

'/ ==============================================
@startuml(id=common) periscope_common_architecture

!$BASEURL="https://raw.githubusercontent.com/somr/architecture/refs/tags/v1.6"


'KUBERNETES
!$POD="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/pod-128.png"
!$DEPLOY="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/deploy-128.png"
!$RS="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/rs-128.png"
!$HPA="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/hpa-128.png"
!$CONFIGMAP="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/cm-128.png"
!$JOB="img:"+$BASEURL+"/icons/kubernetes/resources/labeled/job-128.png"
!$SCH="img:"+$BASEURL+"/icons/kubernetes/control_plane_components/labeled/sched-128.png"
!$API="img:"+$BASEURL+"/icons/kubernetes/control_plane_components/labeled/api-128.png"


'COMMON
!$FILE="img:"+$BASEURL+"/icons/file_manyrecords.png"
!$RECORD="img:"+$BASEURL+"/icons/individualRecord.png"
!$CLOUDERA="img:"+$BASEURL+"/icons/cloudera_logo_icon.png"
!$RESTAPI="img:"+$BASEURL+"/icons/api-cogwheel.png"

left to right direction

skinparam DefaultTextAlignment center
skinparam DefaultAlignment center
skinparam ArrowThickness 5

skinparam title{
	FontSize 40
}

skinparam rectangle{
	backgroundColor #FFFFFF
	roundCorner 25
}

skinparam node<<Infrastructure>>{
	backgroundColor LightBlue
	fontColor DarkBlue
	FontSize 40
}

skinparam rectangle<<Observed>>{
	backgroundColor DarkOrange
	fontColor white
	FontSize 20
}

skinparam rectangle<<Instrumented>>{
	backgroundColor DarkOrange
	fontColor white
	FontSize 20
}

skinparam rectangle<<PeriscopeService>>{
	'backgroundColor LimeGreen
	backgroundColor #A9D18E
    fontColor white
	FontSize 20
}

skinparam rectangle<<ProbePoint>>{
	'backgroundColor ForestGreen
	backgroundColor #A9D18E
    fontColor white
	FontSize 20
}

'GCP
!$GCPCLOUD="img:"+$BASEURL+"/icons/gcp/gcp.png"

!$AIRFLOW="img:"+$BASEURL+"/icons/gcp/airflow.png"
!$BQ="img:"+$BASEURL+"/icons/gcp/bigquery.png"
!$BQPROC="img:"+$BASEURL+"/icons/gcp/bigquery-proc.png"
!$CLOG="img:"+$BASEURL+"/icons/gcp/cloudlogging.png"
!$SECRETS="img:"+$BASEURL+"/icons/gcp/secretsmanager.png"
!$DT="img:"+$BASEURL+"/icons/gcp/datatransfer.png"
!$BUCKET="img:"+$BASEURL+"/icons/gcp/cloudstorage.png"
!$DPROC="img:"+$BASEURL+"/icons/gcp/dataproc.png"
!$PUBSUB="img:"+$BASEURL+"/icons/gcp/pubsub.png"
!$GKE="img:"+$BASEURL+"/icons/gcp/gke.png"
!$CFUNCTION="img:"+$BASEURL+"/icons/gcp/cloudfunction.png"
!$CCOMPOSER="img:"+$BASEURL+"/icons/gcp/ccomposerv2.png"
!$CLOUDSQL="img:"+$BASEURL+"/icons/gcp/cloudsql.png"
!$SCHEDULER="img:"+$BASEURL+"/icons/gcp/scheduler.png"
!$MONITORING="img:"+$BASEURL+"/icons/gcp/monitoring.png"
!$LOOKER="img:"+$BASEURL+"/icons/gcp/looker.png"

'AWS
!$AWSCLOUD="img:"+$BASEURL+"/icons/aws/AWS-Cloud-logo_64.png"
!$LAMBDA="img:"+$BASEURL+"/icons/aws/Arch_Compute/64/Arch_AWS-Lambda_64.png"
!$S3BUCKET="img:"+$BASEURL+"/icons/aws/Arch_Storage/64/Arch_Amazon-Simple-Storage-Service_64.png"
!$EMR="img:"+$BASEURL+"/icons/aws/Arch_Analytics/64/Arch_Amazon-EMR_64.png"
!$EVENTBRIDGE="img:"+$BASEURL+"/icons/aws/Arch_App-Integration/64/Arch_Amazon-EventBridge_64.png"


!$EMRJOB="img:"+$BASEURL+"/icons/aws/Arch_Analytics/64/Res_Amazon-EMR_Cluster_48.png"

!$ATHENA="img:"+$BASEURL+"/icons/aws/Arch_Analytics/64/Arch_Amazon-Athena_64.png"

!$SNS="img:"+$BASEURL+"/icons/aws/Arch_App-Integration/64/Arch_Amazon-Simple-Notification-Service_64.png"
!$SQS="img:"+$BASEURL+"/icons/aws/Arch_App-Integration/64/Arch_Amazon-Simple-Queue-Service_64.png"
!$STEPFN="img:"+$BASEURL+"/icons/aws/Arch_App-Integration/64/Arch_AWS-Step-Functions_64.png"

!$TASK="img:"+$BASEURL+"/icons/aws/Arch_Containers/64/Res_Amazon-Elastic-Container-Service_Task_48.svg"
!$ECS="img:"+$BASEURL+"/icons/aws/Arch_Containers/64/Arch_Amazon-Elastic-Container-Service_64.png"

!$LOGGROUP="img:"+$BASEURL+"/icons/aws/Arch_Management-Governance/64/Res_Amazon-CloudWatch_Logs_48.png"
!$CRON="img:"+$BASEURL+"/icons/aws/Arch_Management-Governance/64/Res_Amazon-CloudWatch_Event-Time-Based_48.png"
!$ALARM="img:"+$BASEURL+"/icons/aws/Arch_Management-Governance/64/Res_Amazon-CloudWatch_Alarm_48.png"

!$LOADBALANCER="img:"+$BASEURL+"/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Elastic-Load-Balancing_64.png"
!$LOADBALANCER_SERVICE="img:"+$BASEURL+"/icons/aws/Arch_Networking-Content-Delivery/64/Res_Elastic-Load-Balancing_Network-Load-Balancer_48.png"

!$RDS="img:"+$BASEURL+"/icons/aws/Arch_Database/64/Arch_Amazon-RDS_64.png"
!$RDS_PG="img:"+$BASEURL+"/icons/aws/Arch_Database/64/Res_Amazon-Aurora-PostgreSQL-Instance_48.png"
!$RDS_MY="img:"+$BASEURL+"/icons/aws/Arch_Database/64/Res_Amazon-Aurora-PostgreSQL-Instance_48.png"

!$SSM="img:"+$BASEURL+"/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Secrets-Manager_64.png"

@enduml
